server:
  port: 9000
spring:
  application:
    name: example-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # group: iogogogo
management:
  endpoints:
    web:
      exposure:
        include: '*'