server:
  port: 8088
spring:
  application:
    name: cloud-admin-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # group: iogogogo
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    nacos-discovery:
      enabled: true # 修改spring.cloud.nacos.discovery.group以后，如果没哟改配置，则不会出现在admin-server
    health:
      show-details: always