server:
  port: 9527
spring:
  application:
    name: cloud-gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true # 启用注册中心自动发现服务
          lower-case-service-id: true # 服务名转小写
