server:
  port: 9020
spring:
  application:
    name: example-consumer-openfeign
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # group: iogogogo
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
management:
  endpoints:
    web:
      exposure:
        include: '*'